export { AlbumController } from "./album.controller.js";
export { ConteudoController } from "./conteudo.controller.js";
export { AutenticacaoController } from "./autenticacao.controller.js";
export { Controller } from "./controller.js";
export { BaseController } from "./base.controller.js";
export { ClassificacaoController } from "./classificacao.controller.js";
export { RevisaoController } from "./revisao.controller.js";
export { TipoController } from "./tipo.controller.js";
export { UtilizadorController } from "./utilizador.controller.js";
